In [1]:
import pandas as pd
import os

In [2]:
tumbol_id_df = pd.read_csv('data/all-tumbol-id.csv')
tumbol_id_df

      tumbol_ID
0        110113
1        110115
2        110117
3        110151
4        110155
...         ...
7580     961106
7581     961151
7582     961203
7583     961204
7584     961301

[7585 rows x 1 columns]

In [3]:
tumbol_df = pd.read_csv('data/tumbon_week1.csv')[['TUMBOL_ID', 'MAP_TUMBOL_ID']]
tumbol_df.columns = ['tumbol_ID', 'MAP_TUMBOL_ID']
tumbol_df

      tumbol_ID  MAP_TUMBOL_ID
0        150603       150603.0
1        150613       150613.0
2        150614       150614.0
3        160208       160208.0
4        160251       160201.0
...         ...            ...
7580     571604       571604.0
7581     600512       600512.0
7582     480708       480708.0
7583     490207       490207.0
7584     490701       490701.0

[7585 rows x 2 columns]

In [5]:
gee_df = pd.read_csv('data/GEE-merge_all.csv')
gee_df

,tumbol_ID,nightlight_stdDev,NDVI_max,NDVI_sum,No2_sum,nightlight_sum,nightlight_mean,sentinel-2_mean_B1,sentinel-2_mean_B2,sentinel-2_mean_B3,...,sentinel-2_MAX_MSK_SNWPRB,sentinel-2_MAX_QA10,sentinel-2_MAX_QA20,sentinel-2_MAX_QA60,2021_waterClass,2000_population,2005_population,2010_population,2015_population,2020_population
0,110116,7.793844,0.206210,1.617781,0.000628,246.711639,27.836933,4878.686263,4328.981804,4103.485673,...,0.013605,0.0,0.0,27.675676,3.403922,2313.110107,3130.494629,4039.519775,5182.693359,6497.666992
1,110113,6.828918,0.281376,0.900175,0.000352,57.910856,14.916433,4663.523546,4118.650328,3852.554245,...,0.000000,0.0,0.0,27.675676,4.392157,2313.597168,3131.154053,4040.370361,5183.785156,6499.035156
2,110112,3.285236,0.220740,2.071562,0.000792,132.800389,7.860747,3107.181809,2840.868680,2897.044992,...,0.027211,0.0,0.0,41.795918,24.415686,2312.866455,3130.164795,4039.093994,5182.147461,6496.982422
3,110101,8.567458,0.197259,1.124520,0.000674,178.035216,20.449991,5057.634642,4490.573551,4241.246816,...,0.000000,0.0,0.0,27.675676,10.145098,2556.893799,3460.424316,4465.253418,5728.908691,7182.470215
4,110114,16.853708,0.170754,0.850994,0.000544,196.963092,32.466444,4980.803080,4552.170181,4303.276420,...,0.000000,0.0,0.0,27.675676,1.329412,2313.597412,3131.154297,4040.370850,5183.785645,6499.036133
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7251,960902,0.934066,0.522976,43.341983,0.000969,49.220389,0.495449,4508.648668,4269.817849,4200.679484,...,0.061644,0.0,0.0,84.164384,0.023529,37.625462,38.406391,37.378792,36.170628,34.202900
7252,961202,0.364483,0.531579,47.586000,0.001067,56.701840,0.493885,4633.852109,4387.132413,4310.327116,...,0.000000,0.0,0.0,70.136986,0.149020,184.519958,188.349731,183.310257,177.385284,167.735306
7253,961203,0.364736,0.495413,21.553906,0.000542,31.385436,0.614597,4953.919851,4662.774451,4567.543671,...,0.095890,0.0,0.0,70.136986,0.011765,302.048492,309.884888,303.126709,294.820068,280.198608
7254,961303,0.882984,0.428108,23.270584,0.000745,76.962373,1.191079,4827.691405,4577.944557,4517.170492,...,0.082192,0.0,0.0,98.191781,0.639216,44.166828,45.083527,43.877274,42.459064,40.149242
7255,961204,0.196093,0.534922,156.805657,0.003578,148.782649,0.374953,4821.083407,4554.927861,4443.712099,...,0.000000,0.0,0.0,70.136986,0.686275,294.895142,301.015808,292.961823,283.492676,268.070343

In [6]:
tesaban_df = tumbol_df[tumbol_df['tumbol_ID'] != tumbol_df['MAP_TUMBOL_ID']]
tesaban_df.index = range(len(tesaban_df))
tesaban_df = tesaban_df.dropna()
tesaban_df = tesaban_df.merge(gee_df, left_on= 'MAP_TUMBOL_ID', right_on='tumbol_ID')
tesaban_df = tesaban_df.drop(['MAP_TUMBOL_ID','tumbol_ID_y'], axis=1)
col_name = list(tesaban_df.columns)
col_name[0] = 'tumbol_ID'
tesaban_df.columns = col_name
tesaban_df.index = tesaban_df.tumbol_ID
tesaban_df = tesaban_df.drop('tumbol_ID', axis=1)
tesaban_df

,nightlight_stdDev,NDVI_max,NDVI_sum,No2_sum,nightlight_sum,nightlight_mean,sentinel-2_mean_B1,sentinel-2_mean_B2,sentinel-2_mean_B3,sentinel-2_mean_B4,...,sentinel-2_MAX_MSK_SNWPRB,sentinel-2_MAX_QA10,sentinel-2_MAX_QA20,sentinel-2_MAX_QA60,2021_waterClass,2000_population,2005_population,2010_population,2015_population,2020_population
tumbol_ID,,,,,,,,,,,,,,,,,,,,,
160251,0.955420,0.491519,48.885329,0.005158,148.419828,1.095333,3906.139397,3680.582046,3625.952611,3461.722402,...,0.000000,0.0,0.0,14.027397,2.058824,83.824516,86.456383,85.020409,83.130112,79.427269
110157,3.777945,0.183798,1.529590,0.000895,210.284411,21.587168,5243.493407,4643.578888,4408.036027,4242.559884,...,0.000000,0.0,0.0,27.675676,0.572549,2313.273438,3130.715820,4039.804932,5183.059570,6498.125488
141252,3.249220,0.307766,2.287356,0.000441,37.815034,4.127925,3630.885602,3457.953568,3419.156748,3224.407194,...,0.000000,0.0,0.0,0.000000,13.956863,340.160919,321.586670,289.875671,259.797241,227.527237
200454,4.858805,0.480832,42.366626,0.006056,965.344433,5.709845,3995.523849,3779.130817,3772.629840,3599.375919,...,0.034247,0.0,0.0,70.136986,10.921569,710.684204,881.702393,1042.959595,1226.653687,1409.783936
210252,7.017785,0.444809,17.966894,0.002656,446.892758,6.873200,4469.689171,4223.115632,4163.006544,3969.275133,...,0.000000,0.0,0.0,56.109589,4.223529,151.251556,192.498474,233.590302,281.832703,332.279877
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
810651,0.697865,0.721631,108.932919,0.002599,141.677458,0.549681,4151.481451,3964.663279,3955.291597,3752.018841,...,0.219178,0.0,0.0,70.136986,1.698039,49.073074,51.694145,51.920578,51.849762,50.597622
900151,9.059903,0.274378,1.741661,0.000200,181.292863,14.120244,5183.173388,4989.340125,4882.262906,4668.562071,...,0.979452,0.0,0.0,56.109589,22.662745,85.388680,88.734108,87.918633,86.612450,83.378830
920652,1.908314,0.498406,11.552165,0.000257,51.481168,1.847930,4970.341878,4758.044981,4675.628853,4439.578563,...,0.013699,0.0,0.0,70.136986,0.580392,218.973663,222.940765,216.414886,208.878555,197.004745
950351,1.370939,0.566638,43.748802,0.001058,136.364822,1.161618,4142.695150,3967.131818,3958.359925,3709.153332,...,0.054795,0.0,0.0,56.109589,0.933333,57.011505,58.787865,59.683434,59.770275,58.996189
960751,0.596792,0.588032,70.902814,0.001599,92.456557,0.532427,4685.621057,4450.964852,4352.485859,4105.004778,...,0.027397,0.0,0.0,70.136986,2.807843,431.444183,440.398956,428.615662,414.761902,392.198334

In [7]:
gee_map_df = tumbol_df.merge(gee_df, on='tumbol_ID', how='left')
gee_map_df = gee_map_df.drop('MAP_TUMBOL_ID',axis=1)
gee_map_df.index = gee_map_df.tumbol_ID
gee_map_df = gee_map_df.drop('tumbol_ID', axis=1)

for i in tesaban_df.index:
    gee_map_df.loc[i] = tesaban_df.loc[i]
    
gee_map_df

,nightlight_stdDev,NDVI_max,NDVI_sum,No2_sum,nightlight_sum,nightlight_mean,sentinel-2_mean_B1,sentinel-2_mean_B2,sentinel-2_mean_B3,sentinel-2_mean_B4,...,sentinel-2_MAX_MSK_SNWPRB,sentinel-2_MAX_QA10,sentinel-2_MAX_QA20,sentinel-2_MAX_QA60,2021_waterClass,2000_population,2005_population,2010_population,2015_population,2020_population
tumbol_ID,,,,,,,,,,,,,,,,,,,,,
150603,1.069607,0.299314,2.731163,0.000483,29.652141,2.755574,4111.642682,3890.549328,3791.031476,3527.905832,...,0.0,0.0,0.0,0.000000,16.643137,239.349228,235.999802,221.866318,207.386322,189.428360
150613,1.403772,0.356083,2.364066,0.000327,27.624538,3.480364,4219.827014,4013.107721,3893.858411,3631.723909,...,0.0,0.0,0.0,0.000000,5.168627,300.903534,310.351105,305.196411,298.410828,285.118805
150614,0.442472,0.287121,5.283816,0.000832,19.186972,0.836498,4255.975882,4040.164796,3911.352942,3639.953836,...,0.0,0.0,0.0,0.000000,18.627451,300.903564,310.351166,305.196442,298.410858,285.118835
160208,0.342014,0.452569,34.945712,0.003651,57.516485,0.532289,4004.171010,3813.136659,3757.018162,3598.613214,...,0.0,0.0,0.0,27.675676,1.352941,73.606766,78.232155,80.881073,83.324783,84.066780
160251,0.955420,0.491519,48.885329,0.005158,148.419828,1.095333,3906.139397,3680.582046,3625.952611,3461.722402,...,0.0,0.0,0.0,14.027397,2.058824,83.824516,86.456383,85.020409,83.130112,79.427269
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
571604,0.507747,0.575624,16.529163,0.000887,42.038495,0.855600,3692.666324,3593.218131,3592.253122,3429.567069,...,0.0,0.0,0.0,28.444444,0.807843,13.921293,14.082339,13.582200,13.024902,12.205482
600512,0.557744,0.485810,12.582013,0.000921,32.738810,0.836680,3243.071224,3165.341759,3208.087384,3065.382721,...,0.0,0.0,0.0,0.000000,1.784314,137.096313,138.330704,135.532745,132.059998,125.765564
480708,0.317847,0.506976,47.500394,0.002123,47.645706,0.420928,4453.204812,4104.708126,4000.245148,3802.805819,...,0.0,0.0,0.0,13.837838,5.341176,69.291878,64.944939,58.037449,51.568016,44.774281
490207,0.278049,0.559364,20.566330,0.000859,23.557479,0.523044,4246.288108,3952.694705,3884.904733,3703.821745,...,0.0,0.0,0.0,14.027397,0.337255,86.881836,94.561287,98.129112,101.249153,102.084785
490701,0.565322,0.573331,8.593868,0.000366,15.511186,0.809528,4687.417399,4291.151131,4191.432839,3992.141161,...,0.0,0.0,0.0,14.027397,0.478431,83.438339,81.214607,75.647423,70.335487,68.526031

In [10]:
gee_NDVI = pd.read_csv('data/GEE-v6_dirty.csv')[['tumbol_ID', 'NDWI','NDBI','NDVI']]
gee_NDVI

      tumbol_ID      NDWI      NDBI      NDVI
0        110116 -0.027396 -0.063092  0.045195
1        110113 -0.061510 -0.125792  0.079897
2        110112 -0.090016 -0.101265  0.102580
3        110101 -0.016719 -0.074339  0.035142
4        110114 -0.026832 -0.061514  0.037557
...         ...       ...       ...       ...
7251     960902 -0.139091 -0.247470  0.166546
7252     961202 -0.130031 -0.242611  0.157671
7253     961203 -0.075155 -0.254523  0.099189
7254     961303 -0.116163 -0.257918  0.142260
7255     961204 -0.037923 -0.231916  0.059920

[7256 rows x 4 columns]

In [11]:
out_df = gee_map_df.merge(gee_NDVI, on='tumbol_ID', how='left')
out_df

,tumbol_ID,nightlight_stdDev,NDVI_max,NDVI_sum,No2_sum,nightlight_sum,nightlight_mean,sentinel-2_mean_B1,sentinel-2_mean_B2,sentinel-2_mean_B3,...,sentinel-2_MAX_QA60,2021_waterClass,2000_population,2005_population,2010_population,2015_population,2020_population,NDWI,NDBI,NDVI
0,150603,1.069607,0.299314,2.731163,0.000483,29.652141,2.755574,4111.642682,3890.549328,3791.031476,...,0.000000,16.643137,239.349228,235.999802,221.866318,207.386322,189.428360,-0.080085,-0.157483,0.116550
1,150613,1.403772,0.356083,2.364066,0.000327,27.624538,3.480364,4219.827014,4013.107721,3893.858411,...,0.000000,5.168627,300.903534,310.351105,305.196411,298.410828,285.118805,-0.104815,-0.164019,0.133885
2,150614,0.442472,0.287121,5.283816,0.000832,19.186972,0.836498,4255.975882,4040.164796,3911.352942,...,0.000000,18.627451,300.903564,310.351166,305.196442,298.410858,285.118835,-0.095662,-0.127946,0.122605
3,160208,0.342014,0.452569,34.945712,0.003651,57.516485,0.532289,4004.171010,3813.136659,3757.018162,...,27.675676,1.352941,73.606766,78.232155,80.881073,83.324783,84.066780,-0.143411,-0.131716,0.160796
4,160251,0.955420,0.491519,48.885329,0.005158,148.419828,1.095333,3906.139397,3680.582046,3625.952611,...,14.027397,2.058824,83.824516,86.456383,85.020409,83.130112,79.427269,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7580,571604,0.507747,0.575624,16.529163,0.000887,42.038495,0.855600,3692.666324,3593.218131,3592.253122,...,28.444444,0.807843,13.921293,14.082339,13.582200,13.024902,12.205482,-0.149335,-0.171552,0.183101
7581,600512,0.557744,0.485810,12.582013,0.000921,32.738810,0.836680,3243.071224,3165.341759,3208.087384,...,0.000000,1.784314,137.096313,138.330704,135.532745,132.059998,125.765564,-0.151394,-0.112406,0.171236
7582,480708,0.317847,0.506976,47.500394,0.002123,47.645706,0.420928,4453.204812,4104.708126,4000.245148,...,13.837838,5.341176,69.291878,64.944939,58.037449,51.568016,44.774281,-0.110787,-0.126529,0.137990
7583,490207,0.278049,0.559364,20.566330,0.000859,23.557479,0.523044,4246.288108,3952.694705,3884.904733,...,14.027397,0.337255,86.881836,94.561287,98.129112,101.249153,102.084785,-0.143770,-0.127380,0.147421
7584,490701,0.565322,0.573331,8.593868,0.000366,15.511186,0.809528,4687.417399,4291.151131,4191.432839,...,14.027397,0.478431,83.438339,81.214607,75.647423,70.335487,68.526031,-0.108383,-0.125153,0.123719

In [12]:
out_df.to_csv('data/gee_processed.csv')